/*
Mobile Interfaces and Usability 1208
Full Sail University
Mobile Development
Professor: Robin Alarcon
PlayIGL Team Management App
Project 2
Jonathan Caraveo 
*/

var json = {
	"member1":{
		"alias": ["Gamer Name:", "Demlok"],
		"fName": ["First Name:", "Johnny"],
		"lName": ["Last Name:", "Caraveo"],
		"eMail": ["Email:", "JohnnyCaraveo@gmail.com"],
		"bDay": ["Birth Date:", "02-14-1987"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "150"],
		"sex": ["Sex:", "Male"],
		"pro": ["Professional:", "Yes"],
		"division": ["Division:", "Central"],
		"league": ["League:", "Major"],
		"notes": ["Notes:", "This is not a test."],
	},
	"member2":{
		"alias": ["Gamer Name:", "Ender"],
		"fName": ["First Name:", "John"],
		"lName": ["Last Name:", "Car"],
		"eMail": ["Email:", "Caraveo@me.com"],
		"bDay": ["Birth Date:", "02-14-1987"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "150"],
		"sex": ["Sex:", "Male"],
		"pro": ["Professional:", "Yes"],
		"division": ["Division:", "West"],
		"league": ["League:", "International"],
		"notes": ["Notes:", "The enemies gate is down."],
	},
	"member3":{
		"alias": ["Gamer Name:", "Bean"],
		"fName": ["First Name:", "Rich"],
		"lName": ["Last Name:", "Gonzales"],
		"eMail": ["Email:", "gonzales@gmail.com"],
		"bDay": ["Birth Date:", "06-14-1987"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "45"],
		"sex": ["Sex:", "Male"],
		"pro": ["Professional:", "No"],
		"division": ["Division:", "West"],
		"league": ["League:", "Major"],
		"notes": ["Notes:", "I want to be a pro gamer."],
	},
	"member4":{
		"alias": ["Gamer Name:", "Xander"],
		"fName": ["First Name:", "Jane"],
		"lName": ["Last Name:", "Doe"],
		"eMail": ["Email:", "JaneDoe@gmail.com"],
		"bDay": ["Birth Date:", "12-23-1987"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "90"],
		"sex": ["Sex:", "Female"],
		"pro": ["Professional:", "Yes"],
		"division": ["Division:", "Central"],
		"league": ["League:", "International"],
		"notes": ["Notes:", "I am a pro."],
	},
	"member5":{
		"alias": ["Gamer Name:", "Demetry"],
		"fName": ["First Name:", "Joe"],
		"lName": ["Last Name:", "Smo"],
		"eMail": ["Email:", "Smo@vensure.com"],
		"bDay": ["Birth Date:", "12-23-1985"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "200"],
		"sex": ["Sex:", "Male"],
		"pro": ["Professional:", "Yes"],
		"division": ["Division:", "East"],
		"league": ["League:", "Major"],
		"notes": ["Notes:", "W00t w00t East Coast."],
	},
	"member6":{
		"alias": ["Gamer Name:", "Locke"],
		"fName": ["First Name:", "Ryan"],
		"lName": ["Last Name:", "Picaso"],
		"eMail": ["Email:", "Picaso@me.com"],
		"bDay": ["Birth Date:", "01-14-1980"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "120"],
		"sex": ["Sex:", "Male"],
		"pro": ["Professional:", "No"],
		"division": ["Division:", "Central"],
		"league": ["League:", "National"],
		"notes": ["Notes:", "I want to be a national pro gamer."],
	},
	"member7":{
		"alias": ["Gamer Name:", "Tyreal"],
		"fName": ["First Name:", "Ariel"],
		"lName": ["Last Name:", "Caraveo"],
		"eMail": ["Email:", "JC@me.com"],
		"bDay": ["Birth Date:", "04-16-1987"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "120"],
		"sex": ["Sex:", "Male"],
		"pro": ["Professional:", "Yes"],
		"division": ["Division:", "East"],
		"league": ["League:", "Major"],
		"notes": ["Notes:", "This is the EAST COAST!"],
	},
	"member8":{
		"alias": ["Gamer Name:", "Sam"],
		"fName": ["First Name:", "Sammy"],
		"lName": ["Last Name:", "Scola"],
		"eMail": ["Email:", "SamTheMan@gmail.com"],
		"bDay": ["Birth Date:", "02-20-1988"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "100"],
		"sex": ["Sex:", "Male"],
		"pro": ["Professional:", "Yes"],
		"division": ["Division:", "West"],
		"league": ["League:", "Major"],
		"notes": ["Notes:", "Trust me, I'm a professional."],
	},
	"member9":{
		"alias": ["Gamer Name:", "Angat"],
		"fName": ["First Name:", "Angelita"],
		"lName": ["Last Name:", "Atwater"],
		"eMail": ["Email:", "Agate@gmail.com"],
		"bDay": ["Birth Date:", "04-14-1987"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "180"],
		"sex": ["Sex:", "Female"],
		"pro": ["Professional:", "Yes"],
		"division": ["Division:", "East"],
		"league": ["League:", "Major"],
		"notes": ["Notes:", "I am an international gamer."],
	},
	"member10":{
		"alias": ["Gamer Name:", "ReyRas"],
		"fName": ["First Name:", "Reynaldo"],
		"lName": ["Last Name:", "Rascoe"],
		"eMail": ["Email:", "reyRas@yahoo.com"],
		"bDay": ["Birth Date:", "04-19-1985"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "160"],
		"sex": ["Sex:", "Male"],
		"pro": ["Professional:", "No"],
		"division": ["Division:", "East"],
		"league": ["League:", "International"],
		"notes": ["Notes:", "I own the international league."],
	},
	"member11":{
		"alias": ["Gamer Name:", "Sidy"],
		"fName": ["First Name:", "Sid"],
		"lName": ["Last Name:", "Spivey"],
		"eMail": ["Email:", "SidSpivey@yahoo.com"],
		"bDay": ["Birth Date:", "03-20-1990"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "110"],
		"sex": ["Sex:", "Male"],
		"pro": ["Professional:", "Yes"],
		"division": ["Division:", "Central"],
		"league": ["League:", "Major"],
		"notes": ["Notes:", "I am a Major Player :)"],
	},
	"member12":{
		"alias": ["Gamer Name:", "FeJo"],
		"fName": ["First Name:", "Jonnie"],
		"lName": ["Last Name:", "Janicki"],
		"eMail": ["Email:", "Janicki@me.com"],
		"bDay": ["Birth Date:", "03-24-1990"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "125"],
		"sex": ["Sex:", "Female"],
		"pro": ["Professional:", "No"],
		"division": ["Division:", "East"],
		"league": ["League:", "National"],
		"notes": ["Notes:", "I am a nationalist."],
	},
	"member13":{
		"alias": ["Gamer Name:", "Leshay"],
		"fName": ["First Name:", "Lesha"],
		"lName": ["Last Name:", "Lai"],
		"eMail": ["Email:", "Lai@yahoo.com"],
		"bDay": ["Birth Date:", "04-20-1985"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "150"],
		"sex": ["Sex:", "Female"],
		"pro": ["Professional:", "No"],
		"division": ["Division:", "West"],
		"league": ["League:", "National"],
		"notes": ["Notes:", "Nationalist and West."],
	},
	"member14":{
		"alias": ["Gamer Name:", "Atwata"],
		"fName": ["First Name:", "Angelita"],
		"lName": ["Last Name:", "Atwater"],
		"eMail": ["Email:", "Atwater@hotmail.com"],
		"bDay": ["Birth Date:", "01-10-1970"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "155"],
		"sex": ["Sex:", "Female"],
		"pro": ["Professional:", "Yes"],
		"division": ["Division:", "Central"],
		"league": ["League:", "National"],
		"notes": ["Notes:", "Central Gamer in for the American Nation!"],
	},
	"member15":{
		"alias": ["Gamer Name:", "DD"],
		"fName": ["First Name:", "Darrin"],
		"lName": ["Last Name:", "Deines"],
		"eMail": ["Email:", "DD@yahoo.com"],
		"bDay": ["Birth Date:", "05-10-1995"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "200"],
		"sex": ["Sex:", "Male"],
		"pro": ["Professional:", "Yes"],
		"division": ["Division:", "East"],
		"league": ["League:", "International"],
		"notes": ["Notes:", "I AM INTERNATIONAL!"],
	},
	"member16":{
		"alias": ["Gamer Name:", "Rascae"],
		"fName": ["First Name:", "Reynaldo "],
		"lName": ["Last Name:", "Rascoe"],
		"eMail": ["Email:", "Rascoe@hotmail.com"],
		"bDay": ["Birth Date:", "02-14-1965"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "125"],
		"sex": ["Sex:", "Male"],
		"pro": ["Professional:", "No"],
		"division": ["Division:", "West"],
		"league": ["League:", "Major"],
		"notes": ["Notes:", "I dominate the Major League."],
	},
	"member17":{
		"alias": ["Gamer Name:", "AAmsler"],
		"fName": ["First Name:", "Annie"],
		"lName": ["Last Name:", "Amsler"],
		"eMail": ["Email:", "JohnnyCaraveo@gmail.com"],
		"bDay": ["Birth Date:", "02-14-1987"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "150"],
		"sex": ["Sex:", "Female"],
		"pro": ["Professional:", "Yes"],
		"division": ["Division:", "International"],
		"league": ["League:", "Major"],
		"notes": ["Notes:", "This is not a test."],
	},
	"member18":{
		"alias": ["Gamer Name:", "VV"],
		"fName": ["First Name:", "Valencia"],
		"lName": ["Last Name:", "Villela"],
		"eMail": ["Email:", "vv@gmail.com"],
		"bDay": ["Birth Date:", "04-20-1960"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "120"],
		"sex": ["Sex:", "Female"],
		"pro": ["Professional:", "No"],
		"division": ["Division:", "Central"],
		"league": ["League:", "International"],
		"notes": ["Notes:", "This is international!"],
	},
	"member19":{
		"alias": ["Gamer Name:", "Tiny"],
		"fName": ["First Name:", "Tempie"],
		"lName": ["Last Name:", "Torgeson"],
		"eMail": ["Email:", "TT@gmail.com"],
		"bDay": ["Birth Date:", "03-15-1987"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "200"],
		"sex": ["Sex:", "Male"],
		"pro": ["Professional:", "Yes"],
		"division": ["Division:", "East"],
		"league": ["League:", "Major"],
		"notes": ["Notes:", "I am Tiny."],
	},
	"member20":{
		"alias": ["Gamer Name:", "TMan"],
		"fName": ["First Name:", "Tomas"],
		"lName": ["Last Name:", "Touchton"],
		"eMail": ["Email:", "Tomas@gmail.com"],
		"bDay": ["Birth Date:", "12-14-1987"],
		"language": ["Language:", "English"],
		"skill": ["Skill:", "300"],
		"sex": ["Sex:", "Male"],
		"pro": ["Professional:", "Yes"],
		"division": ["Division:", "West"],
		"league": ["League:", "Major"],
		"notes": ["Notes:", "I am the youngest pro gamer."],
	}
}